// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { existsSync } from "node:fs";
import { defineConfig } from "prisma/config";

const nodeEnv = process.env["NODE_ENV"] ?? "development";
const envFile = `.env.${nodeEnv}.local`;
const fallbackEnvFile = `.env.${nodeEnv}`;
const envPath = existsSync(envFile) ? envFile : fallbackEnvFile;
loadEnv({ path: envPath });

export default defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
	},
	datasource: {
		url: process.env["DATABASE_URI"],
	},
});
